// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyboawhcwawcovwakhnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5Ym9hd2hjd2F3Y292d2FraG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTE4ODcsImV4cCI6MjA2NDU2Nzg4N30.TeU8-UUow4XGfKsSLMwqaxlJfG8Vk5NgFUeWAWw76RE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);